stages:
  - build
  - test

job1:
  stage: build
  script:
    - apt-get update && apt-get -y upgrade
    - apt-get -y install ocaml libgcrypt20-dev ocaml-findlib opam m4
    - cd obliv-c/
    - apt-get -y install ocamlbuild
    - ./configure
    - CFLAGS=-D_Float128=double make
    - cd ../absentminded-crypto-kit
    - export OBLIVC_PATH=../obliv-c/
    - CFLAGS=-D_Float128=double make
    - cd ../leos_code/mpfss/make


