stages:
  - build
  - test

job1:
  stage: build
  script:
    - sudo apt-get update && sudo apt-get -y upgrade
    - apt-get install ocaml libgcrypt20-dev ocaml-findlib opam m4
    - cd obliv-c/
    - ./configure && make
