image: gitlab.informatik.hu-berlin.de:4567/ti/software/bazel-builder:latest

stages:
  - build
  - test

job1:
  stage: build
  script:
    - cd obliv-c/
    - ./configure
    - CFLAGS=-D_Float128=double make
    - cd ../absentminded-crypto-kit
    - export OBLIVC_PATH=../obliv-c/
    - CFLAGS=-D_Float128=double make
    - cd ../leos_code/mpfss/make

