stages:
  - build
  - test

job1:
  stage: build
  script:
    - apt-get update && apt-get -y upgrade
    - apt-get -y install ocaml libgcrypt20-dev ocaml-findlib opam m4
    - cd obliv-c/
    - opam init --auto-setup
    - opam install -y ocamlbuild
    - ls -la /usr/bin
    - which ocamlbuild
    - ./configure && make

