stages:
  - build
  - test

job1:
  stage: build
  script:
    - apt-get update && apt-get -y upgrade
    - apt-get -y install ocaml libgcrypt20-dev ocaml-findlib opam m4
    - apt-get -y install ocamlbuild
    - sudo apt-get install openjdk-8-jdk
    - sudo add-apt-repository ppa:webupd8team/java
    - sudo apt-get update && sudo apt-get install oracle-java8-installer
    - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
    - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
    - sudo apt-get update && sudo apt-get install bazel
    - sudo apt-get install --only-upgrade bazel
    - bazel build //code_master/cuckoo:mpfss_cuckoo 


