image: gitlab.informatik.hu-berlin.de:4567/ti/software/bazel-builder:latest

stages:
  - build
  - test

job1:
  stage: build
  script:
    - pacman --noconfirm -Syu ocaml ocaml-findlib opam
    - opam init --disable-sandboxing -y
    - opam switch create -y 4.06.0
    - eval `opam config env`
    - opam install -y camlp4 ocamlfind ocamlbuild batteries
    - cd obliv-c/
    - ./configure
    - CFLAGS=-D_Float128=double make
    - cd ../absentminded-crypto-kit
    - export OBLIVC_PATH=../obliv-c/
    - CFLAGS=-D_Float128=double make
    - cd ../leos_code/mpfss/make

