load("@com_github_schoppmp_rules_oblivc//oblivc:oblivc.bzl", "oblivc_library")

oblivc_library(
    name = "create_structs",
    srcs = ["create_structs.c"],
    hdrs = [    "create_structs.h",
                "create_structs.oh",
           ],
    visibility = ["//visibility:public"],

    #copts = ["-DDEBUG"], 
)

