load("@com_github_schoppmp_rules_oblivc//oblivc:oblivc.bzl", "oblivc_library")


cc_library(
    name = "dbg",
    hdrs = ["dbg.h"],
    visibility = ["//visibility:public"],
)

oblivc_library(
    name = "util",
    srcs = ["util.c"],
    hdrs = ["util.h"],
    visibility = ["//visibility:public"],
)
